forcedotcom/packaging

- src/interfaces/index.ts
- src/interfaces/packagingInterfacesAndType.ts
- src/package/index.ts
- src/package/package.ts
- src/package/package2Version.ts
- src/package1/index.ts
- src/package1/package1Version.ts
- test/.eslintrc.js
- test/package/package2VersionTest.ts
- test/package/packageTest.ts
- test/package1/package1VersionTest.ts
> chore: stub package and pkg version classes for 1/2 gp

- src/interfaces/packagingInterfacesAndType.ts
- src/interfaces/packagingSObjects.ts
- src/package/packageVersion.ts
- src/package/packageVersionCreate.ts
- src/package/packageVersionCreateRequestReport.ts
- src/package/packageVersionReport.ts
- src/utils/packageUtils.ts
- test/package/packageTest.nut.ts
> fix: add pv report and pvc report

- package.json
- src/package/packageProfileApi.ts
- yarn.lock
this fixes something the security scanner doesn't like.
FWIW: if you know the type (Profile) I'd suggest using fastXmlParser and the jsforce typings for profiles rather than doing this weird DOM stuff.
> fix: use regular xmlDom package

- src/interfaces/packagingSObjects.ts
- src/package/packageInstall.ts
- test/package/package.test.ts
- test/package/packageInstall.test.ts
Adds unit tests.  Small changes to typing, casing, and waitForPublish polling.
@W-10832794@
> fix: unit tests and type updates

- src/interfaces/packagingInterfacesAndType.ts
- src/interfaces/packagingSObjects.ts
> fix: add missing property to package2version

- src/package/package.ts
- src/package/packageVersion.ts
- src/package/packageVersionCreate.ts
- src/utils/packageUtils.ts
- test/package/packageTest.nut.ts
> fix: package version. now stored in packdir in sfdx project

- src/interfaces/packagingInterfacesAndType.ts
- src/package/packageVersionReport.ts
- src/utils/packageUtils.ts
- test/package/packageTest.nut.ts
@W-11444248@
Changes needed in library to support command package:version:report and package:version:create:report
> fix: modify pvr types

- src/utils/packageUtils.ts
- test/package/packageTest.nut.ts
@W-11644909@
Corrects the generation of new package alias entries
> fix: correct package alias generation

- .mocharc.json
- src/package/packageVersion.ts
- src/package/packageVersionCreate.ts
> fix: manage aliases properly

- src/utils/packageUtils.ts
> fix: remove hard coded string

- src/interfaces/packagingInterfacesAndType.ts
- src/package/package.ts
- test/package/packageTest.nut.ts
@W-10832873@
adds `Package.update` method
adds NUT
> fix: add Package.update method, NUT

- messages/messages.md
- messages/packageVersionCreate.md
- messages/profile-api.md
- src/package/packageAncestry.ts
- src/package/packageProfileApi.ts
> fix: apply fixes from qa issues

- package.json
- test/package/packageTest.nut.ts
- test/packageList.nut.ts
- yarn.lock
Use latest cli-plugins-testkit
@W-11823417@
> chore: use latest testkit

- package.json
- yarn.lock
> fix: bump sfdx-core dep

- src/package/packageVersionCreate.ts
- src/package/packageVersionList.ts
- src/package/packageVersionReport.ts
> fix: logger should not be initialized during module load

- messages/package_version_create.md
- package.json
- src/interfaces/packagingInterfacesAndType.ts
- src/package/packageVersionCreate.ts
- test/package/packageVersionCreate.test.ts
- yarn.lock
@W-11903179@
added path as an option to pass into pvc
modified resolution of package id and package dir to use packageId or path
> fix: account for aliasOrId or apth for package ver create

- package.json
- yarn.lock
sdr major version
@W-11590389@
> fix(deps): sdr7

- messages/package_version_create.md
- src/package/packageProfileApi.ts
- src/package/packageVersionCreate.ts
- test/package/packageVersionCreate.test.ts
> fix: guard against empty component set

- messages/package.md
- messages/package_version_create.md
> fix: audit package lib messages

- messages/package_ancestry.md
- messages/package_install.md
- messages/package_version_create.md
- messages/pkg_utils.md
> fix: modified additional messages

- src/package/packageVersionCreate.ts
- yarn.lock
> fix: remove objects that cause circular errors in logging

- CONTRIBUTING.md
- DEVELOPING.md
add doc for how to develop in the packaging lib
@W-11949409@
> fix: add doc for how to develop in the packaging lib

- src/interfaces/packagingInterfacesAndType.ts
> fix: fix code cov percentage property name

- .github/workflows/onPushToMain.yml
Missed this in the last PR.  Need to enable the workflow for the docs to publish.
@W-11949409@
> fix: enable docs workflow

- messages/package_version.md
- package.json
- src/package/packageVersion.ts
- test/package/packageVersion.test.ts
> fix: create alias for new 04t picks first pkg alias

- README.md
- src/package/package.ts
- src/package/packageVersion.ts
- src/package/subscriberPackageVersion.ts
- src/package1/package1Version.ts
more & better docs
@W-11949409@
> chore: lint fixes

- DEVELOPING.md
Add doc to DEVELOPING.md about how to use the REPL script.
@W-11949409@
> fix: add docs for repl script

- .github/workflows/failureNotifications.yml
- .github/workflows/test.yml
[@W-11976301@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11976301)
> sync files

- src/interfaces/packagingInterfacesAndType.ts
- src/interfaces/packagingSObjects.ts
- src/package/packageVersionCreate.ts
- src/package/packageVersionList.ts
- test/package/packageVersionCreate.test.ts
(Had to redo this because couldn't get retroactive commit signing to work....)
@W-11824088@ Add language to package version commands: create and list.
Prev PR: https://github.com/forcedotcom/packaging/pull/154
> Add language support for 2GP 

- src/interfaces/packagingInterfacesAndType.ts
- src/package/packageVersionList.ts
@W-11824088@ Fixes for language work...
> feat: Language fixes

- messages/package_version.md
- src/package/package.ts
- src/package/subscriberPackageVersion.ts
removes unused messages and adds missing messages
Running `sf dev audit messages` after this change reports nothing found (which is good).
@W-12236626@
> fix: remove unused messages and add missing messages

- LICENSE.txt
- src/package/package.ts
> fix: remove alias requirement when constructing a Package

- src/package/subscriberPackageVersion.ts
@W-12432030@
exposes a public method to wait for the SPV to be replicated and available to query
> fix: expose waitForPublish method on SPV class

- src/package/packageInstall.ts
- test/package/subscriberPackageVersionInstall.test.ts
Modifies the query code to be more optimized and handles query errors better, particularly for `PACKAGE_UNAVAILABLE`.
@W-12432030@
> fix: update query code and error handling

- messages/package.md
- src/interfaces/packagingInterfacesAndType.ts
- src/interfaces/packagingSObjects.ts
- src/package/package.ts
- test/package/package.test.ts
This is the prerequisite for https://github.com/salesforcecli/plugin-packaging/pull/325
> feat: add AppAnalyticsEnabled option to PackageUpdateOptions

- package.json
- src/package/subscriberPackageVersion.ts
- yarn.lock
> fix(deps): core4, dep bumps

- messages/package_version.md
- src/package/packageVersion.ts
- src/utils/index.ts
- src/utils/packageUtils.ts
- test/package/packageTest.nut.ts
- test/utils/packageUtils.test.ts
Adds a static method to the `PackageVersion` class for querying the `Package2Version` SObject.
@W-13650725@
> feat: support querying the Package2Version SObject from PackageVersion

- .github/workflows/onRelease.yml
Updates onRelease.yml to match current standards
> onRelease update

- package.json
- yarn.lock
[@W-13586057@](https://gus.lightning.force.com/a07EE00001Tl80JYAR)
> fix(deps): core5

- package.json
- yarn.lock
> fix(deps): bump sdr for new types

- src/package/packageVersionCreate.ts
> fix: env var to sf

- CONTRIBUTING.md
- src/package/packageVersionCreate.ts
> refactor: structured clone

- src/package/subscriberPackageVersion.ts
As per this [discussion](https://github.com/forcedotcom/cli/discussions/2625). If there are unit tests needed, please let me know. I didn't see any existing unit tests for the existing getters, but I am happy to add them if needed.
> feat: add dependencies getter

- src/package/packageVersionCreateRequest.ts
`0`'s falsiness strikes again
@W-14898097@
> fix: zero handling

- package.json
- src/package/packageVersionCreate.ts
- yarn.lock
> fix: bump SDR, update logic for optional properties

- package.json
- src/interfaces/packagingInterfacesAndType.ts
- src/package/profileRewriter.ts
- yarn.lock
@W-13565856@
trying to test https://github.com/forcedotcom/schemas/pull/85
meant to QA ^
only found usages for the new `@salesforce/types` though
> chore: use @salesforce/types

- package.json
- src/interfaces/packagingInterfacesAndType.ts
- src/package/packageVersionList.ts
- test/package/packageVersionList.test.ts
- yarn.lock
@W-11167396@
adds a `branch` option to filter package version list to only show that branch
> feat: add a branch parameter/filter to PVL

- package.json
- yarn.lock
> fix: bump core and kit

- package.json
- test/package/subscriberPackageVersion.test.ts
- yarn.lock
> test: fix UT

- messages/subscriber_package_version.md
- package.json
- test/package/subscriberPackageVersion.test.ts
- yarn.lock
ref: https://github.com/forcedotcom/cli/issues/2921
@W-16009913@
updates an error message when a propagation delay could occur as well
> docs: update error message to provide alternative scenario

- package.json
> fix: bump major

- src/package/packageCreate.ts
> fix: fix mpd paths packages

- src/interfaces/packagingInterfacesAndType.ts
- src/interfaces/packagingSObjects.ts
- src/package/packageVersion.ts
- src/package/packageVersionList.ts
- src/package/packageVersionReport.ts
- test/package/packageTest.nut.ts
- test/package/packageVersionList.test.ts
Follow up from - https://github.com/forcedotcom/packaging/pull/591/commits
> feat: display validated-async in version list and report

- src/interfaces/bundleSObjects.ts
- src/package/packageBundle.ts
- test/package/bundleList.test.ts
near copy past of package list implementation
> feat: created bundle list

- src/package/packageBundleVersionCreate.ts
- test/package/bundleVersionCreate.test.ts
this:
[
{"packageVersion": "pkgA@1.1"},
{"packageVersion": "pkgB@2.0"}
]
instead of this:
[
04txx0000004HPuAAM,
04txx0000004HOIAA2
]
> fix: added proper parsing of definition file

- package.json
- yarn.lock
> Bump schemas

- src/interfaces/packagingInterfacesAndType.ts
- src/package/packageVersionCreate.ts
- test/package/packageTest.nut.ts
If `calculateTransitiveDependencies` is specified in packageDir on version:create it is included in the Package2VersionCreateRequest.
@W-17561779@
> W-17561779: feat: support for calculateTransitiveDependencies field

- messages/bundle_version_create.md
- src/package/packageBundleVersionCreate.ts
- test/package/bundleVersionCreate.test.ts
Resovles 0.NEXT into 0.2 when 0.1 is present.
> feat: added handling of next versioning

- messages/package_version_dependency.md
- package.json
- src/interfaces/packagingInterfacesAndType.ts
- src/package/package.ts
- src/package/packageVersionDependency.ts
- test/package/packageVersionDependencies.test.ts
- yarn.lock
[@W-17561980@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000027hh2GYAQ/view)
- Created nodes and edges according to the DependencyGraphJson. Nodes contain additional information including Package Name, Version Number, 04t ID. Edges contain a 04t source string and 04t target string.
- Call the produce() function to output nodes and edges in DOT code format and included output according to verbose and edge direction flag
https://github.com/forcedotcom/packaging/pull/762
> W-17561980 Verified GPG Signing Outputs DOT Code for DisplayDependencies Command
