forcedotcom/packaging

- messages/package_version.md
- src/interfaces/packagingInterfacesAndType.ts
- src/package/packageVersion.ts
- src/package/packageVersionReport.ts
- test/package/packageTest.nut.ts
- test/package/packageVersionCreate.test.ts
Changes `PackageVersion` to be more of a proper class than a collection of utility functions.  Creating an instance of the class will have meaningful methods.  Static methods are used when there isn't enough information to return an instance such as when creating a new package version.
E.g.,
```
const pkgVersion = new PackageVersion({ connection, project, idOrAlias });
await pkgVersion.delete();
```
or
`PackageVersion.create({ options });`
@W-11819142@
> refactor: change PackageVersion to have static and instance methods

- src/package/packageVersion.ts
Changes the `list` function, which returns a list of matching PackageVersions given an array of 0Ho (or aliases) and filtering options, to be static and take additional args for Connection and SfProject.  This is necessary to adopt the PackageVersion refactoring effort in the plugin.
@W-11819142@
> refactor: change list function to be static

- src/interfaces/packagingInterfacesAndType.ts
- src/package/packageConvert.ts
- src/package/packageVersionCreate.ts
- test/package/packageConvert.test.ts
- test/package/packageVersionCreate.test.ts
- test/package/uninstallPackage.test.ts
@W-11975912@
stubs `SDR.convert` which was taking a while on the PVC UTs
adds an option to bypass the default polling of 5 seconds for another operation to increase UT speed
went from ~70s to ~13s 🎉
> test: stub SDR's convert method, add arguments for polling override

- .gitignore
- package.json
- scripts/repl.js
Adds a repl script for easy API testing.
@W-11949409@
Run it via `yarn repl`.  It starts a debugger for attachment and makes the 4 main classes available for testing.  It's also simple to get an org connection and SfProject instance for use with the APIs.
> fix: add repl script

- src/package/packageVersionCreate.ts
@W-12349329@
- modify validation to first find a package in package dirs if 0Ho is provided
- capture the id as the packageName
- If more than one pkg dir is found that references the same id, defer to alias lookups
> fix: search for pkg dir by pkg id

- src/package/packageVersionCreate.ts
- test/package/packageVersionCreate.test.ts
If a language was defined in an org file descriptor used for a package version create, it would set that as an option on the package version create request.  This fix removes that.
Also, the language option is removed unless an org connection of API version 57.0 or higher is used.
@W-12377800@
> fix: do not add language from org descriptor to pvc request object

- messages/package_version_create.md
- package.json
- src/interfaces/packagingInterfacesAndType.ts
- src/package/packageConvert.ts
- src/package/packageVersionCreate.ts
- test/package/packageConvert.test.ts
- test/package/packageVersionCreate.test.ts
What does this PR do?
Adds optional seedMetadata so unpackageable metadata can be pushed to the build org that the packaged metadata depends on, such as StandardValueSets.
What issues does this PR fix or reference?
@W-12204966@
> feat: adds support for seed metadata to both the convert and package version create commands

- src/package/packageVersionCreate.ts
The warnOptions was causing a circular structure when versionName was not in sfdx-project.json.  This removes them, since it's not interesting to see in the logs anyway.
@W-12498587@
https://github.com/forcedotcom/cli/issues/1907
> fix: remove warn options from log message

- src/interfaces/packagingInterfacesAndType.ts
- src/interfaces/packagingSObjects.ts
- test/package/subscriberPackageVersionInstall.test.ts
@W-12394717@ Update the PackageInstallRequest interfaces to include the new SkipHandlers field. The SkipHandlers field accepts a list of package install handlers that can be optionally skipped in order to improve the performance speed of the install/upgrade.
> @W-12394717@ Update interfaces for PackageInstallRequest API with SkipHandlers

- src/interfaces/packagingSObjects.ts
@W-12394717@ PackageInstallRequest SkipHandlers should be a string value in order to accommodate the potential for a list of handlers to skip in the future.
> feat: for expandability, PackageInstallRequest should be a string value

- src/interfaces/packagingSObjects.ts
Change type definition for `PackageInstallRequest.SkipHandlers` to allow null.
@W-00000000@
> fix: skip handlers are nullable

- src/package/packageVersionCreate.ts
What does this PR do?
Fixes package version create so profiles are excluded from the unpackaged metadata directory if code coverage is not specified.
@W-12572895@
> fix: adds support for seed metadata to both the convert and package version create commands

- src/utils/packageUtils.ts
- test/utils/packageUtils.test.ts
Fixes the getPackageVersionStrings() function to properly chunk a large query into multiple, smaller queries when the where clause is too large.
@W-13083719@
> fix: properly chunk query for getPackageVersionStrings

- src/package/packageVersionCreate.ts
- test/package/packageVersionCreate.test.ts
As per @avesolovksyy feedback over [here](https://github.com/forcedotcom/cli/issues/2183) I have added 2 additional unit tests which I believe better describe the intended behaviour and amended the branch checking condition to resolve the regressions.
> fix: added unit tests to better describe branch version selection behaviour and corrected issues

- src/package/packageInstall.ts
> the freq is set in the plugin now, so this PR isn't required to close the gh issue.  This change is to prevent other library consumers from hitting the same bug the plugin was.
plugin library passes around the `PackageInstallOptions`.  If you pass any options, it eventually gets to here
https://github.com/forcedotcom/packaging/blob/b7c470d07cfb0915752c37a84fbde04c534fc12d/src/package/packageInstall.ts#L199
where an undefined `frequency` will become `0`.  It looks like the intent was to have a 5 sec default.  So now both defaults are applied when options are sent BUT freq or timeout aren't included in those options.
https://github.com/forcedotcom/cli/issues/2319
[@W-13797305@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001WeCjbYAF/view)
> fix: use default polling freq

- src/package/packageProfileApi.ts
@W-13652536@ CLI regression causes version:create to fail if Admin.profile was previously in the package.
> fix: prevent profile being filtered out from the package

- src/package/packageProfileApi.ts
- test/package/packageVersionCreate.test.ts
During package version creation, profiles are only searched within package directories.
@W-13932401@
https://github.com/forcedotcom/cli/issues/2336
> fix: profiles are searched only within package directories

- src/package/packageInstall.ts
there's a message in the caught error, which isn't making it out into the UI.  This adds the underlying message into the actions 
@W-14095032@
https://github.com/forcedotcom/cli/issues/2434
bug repro: 
create a scrach org, then try to deploy this package to it (the pkg has an install key so this should error out).
`sf package:install --package 04t4p00000281x3AAA --publish-wait 60 --wait 60`
nicest if combined with https://github.com/salesforcecli/sf-plugins-core/pull/407
> fix: show underlying error message for pkgInstall errors

- messages/package.md
- test/package/packageVersionMetadataRetrieve.test.ts
@W-14221604@
Access to the MetdataPackageVersion.MetadataZip field has been restricted. Updating the error message while we work to get the `package version retrieve` command ready for general consumption.
> fix: revise error message for package version retrieve command

- package.json
- yarn.lock
bumps oclif/core to v3
lib only uses the `Tree` class:
https://github.com/search?q=repo%3Aforcedotcom%2Fpackaging%20%2F%5C%40oclif%5C%2Fcore%2F&type=code
deep import path is still valid on v3:
v3 changes:
https://github.com/oclif/core/pulls?q=is%3Apr+v3+author%3Amdonnalley
> fix: bump oclif/core to v3

- test/package/packageTest.nut.ts
The test was running into 10k query limit, so limiting the list results to the last 5 days should fix things.
> fix: limit package version list test to last 5 days

- src/package/packageVersion.ts
- test/package/packageVersion.test.ts
Adds the request id to the error message when the `package version create` command times out. This Id can be used with `sf package version create report -i THE_ID` to look up the status of the version creation.
Added info to the `error.message` and also added the id as `VersionCreateRequestId` using `setData` on `SfError`. The key for this was derived from [these docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_unlocked_pkg_create_pkg_ver.htm)
Sidenote: The `applyErrorAction` ([source](https://github.com/forcedotcom/packaging/blob/6abaa79d0a9bb744ec0a3675a4e02dbee0f78600/src/utils/packageUtils.ts#L112)) does not appear to be working as expected. The `action` property is being stripped off when the error is thrown.
QA: 
- Pull branch
- `yarn compile` …
> fix: add id on version create timeout

- src/utils/packageUtils.ts
- test/package/packageVersionCreate.test.ts
The creation of the scratch org (build org) during the “package version create” command results in the org created without snapshot, because the snapshot property is null, even though the snapshot is specified in the scratch org definition file as "snapShot". 
While the scratch org is successfully created using the ‘snapShot’ property (uppercase ‘S’) with the “scratch org create” command. We should match this behavior.
- Actual Result
Scratch org (build org) created without the properties of Snapshot. For ex: Profiles that are created on the snapshotted org are missing in the build org.
- Expected Result
Scratch org (build org) should be created with the properties of Snapshot. The "package version create" command should not fail due to a missing custom profile that was from the …
> @W-14742535@ Fix: definition-file keys case sensitivity

- package.json
- src/interfaces/packagingInterfacesAndType.ts
- src/package/packageVersionCreate.ts
- test/package/packageVersionCreate.test.ts
- yarn.lock
[@W-14842023@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001iQVLhYAO/view)
Add support for additional properties in sfdx-project.json to allow specifying permission sets and permission set licenses to the build org user for package metadata deploy during the package version creation process.
> feat: add PS/PSL for package metadata options to sfdx-project.json

- src/package/packageVersionList.ts
- src/package/packageVersionReport.ts
- test/package/packageTest.nut.ts
- test/package/packageVersionList.test.ts
Move the non-CodeCoverage fields from the verbose query to the default query so that JSON responses are more accurate.
@W-15398724@
> fix: move verbose field to default fields

- .github/workflows/test.yml
- package.json
- yarn.lock
Adds the plugin-packaging NUTs to the test workflow for GHA so we can know if changes to this library will break the plugin.
@W-15534460@
> test: add xNUTs to GHA

- package.json
- src/package/packageAncestry.ts
- yarn.lock
Use `object-treeify` instead of `@ocilf/core`
Two bummers:
- We have to use v2 instead of latest (v4) because ESM
- No types on `object-treeify` (https://github.com/blackflux/object-treeify/issues/1077)
@W-15576593@
> fix: use object-treeify directly

- package.json
- src/package/packageInstall.ts
- src/package/subscriberPackageVersion.ts
- test/package/packageTest.nut.ts
- test/package/subscriberPackageVersion.test.ts
- yarn.lock
Changes error handling to either re-throw the original message, or throw a new error using the old error as context.
GH Issue: https://github.com/forcedotcom/cli/issues/2882
@W-15832085@
> fix: better error handling when installing packages

- package.json
- src/interfaces/packagingInterfacesAndType.ts
- src/package/packageConvert.ts
- src/package/packageCreate.ts
- src/package/packageDelete.ts
- src/package/packageVersion.ts
- src/package/packageVersionCreate.ts
- src/package/packageVersionRetrieve.ts
- src/package1/package1Version.ts
- src/utils/packageUtils.ts
- test/package/ancestry.nut.ts
- test/package/packageTest.nut.ts
- test/package/packageVersionCreate.test.ts
- test/package/subscriberPackageVersion.test.ts
- yarn.lock
uses types for sfProject, PackageDir etc from sfdx-core
refactor some un-bundleable geLogger stuff
othr basic TS cleanup (remove assertions, simplify types)
> refactor: type consolidation

- .github/workflows/test.yml
- messages/package_version.md
- package.json
- src/interfaces/packagingInterfacesAndType.ts
- src/package/package.ts
- src/package/packageAncestry.ts
- src/package/packageDelete.ts
- src/package/packageVersion.ts
- src/package/packageVersionReport.ts
- yarn.lock
This PR updates some packaging classes to make `SfProject` optional.
See: https://github.com/salesforcecli/plugin-packaging/pull/771
Most of these classes were taking an `SfProject` instance along with a possible package ID **or** alias (defined in sfdx-project.json). By making `SfProject` optional, consumers of the library can call it without having to create a dummy sfdx-project.
Note for review:
there are classes/methods that do need a project b/c they write stuff on it after a package operation, most of these aren't affected by this change (`PackageVersion.updateProjectWithPackageVersion` was updated to throw if there's no project).
QA:
Check the plugin-packaging PR linked above, with this branch linked (or the prerelease) you should be able to use the listed commands outside a …
> feat: make `SfProject` optional

- LICENSE.txt
- package.json
- src/interfaces/packagingInterfacesAndType.ts
- src/interfaces/packagingSObjects.ts
- src/package/package.ts
- src/package/packageVersionCreateRequest.ts
- src/package/packageVersionReport.ts
- test/package/packageConvert.test.ts
- test/package/packageTest.nut.ts
- test/package/packageVersionCreate.test.ts
- yarn.lock
@W-17653027@
- Added TotalSizeOfMetadataFiles as queryable field only for api version > 63
- Added TotalSizeOfMetadataFiles field as part of PackageVersionReportResult and PackageVersionCreateRequestResult.
- PackageVersionCreateRequestResult is queried on package version creation status. On success , TotalSizeOfMetadataFiles will be used to log warning if it exceeds predefined limit(This will be added in plugin-packaging)
> W-17653027: add totalsizeofmetadatafiles field

- src/package/packageVersion.ts
@W-17369132@
This fixes an issue with the addition of DeveloperUsePkgZip to the Package2VersionFields. That field is not visible unless the user has been assigned the DownloadPackageVersionZips user permission. The field is only need for doing a package version retrieve, so filter it out for other use cases so it doesn't cause failures in other commands if the user perm is not granted to the user.
> W-17369132: feat: ignore DeveloperUsePkgZip for id retrieve
